x-config-shared: &config-shared
  networks:
    - traefik_proxy
  pull_policy: always

services:
  blue:
    <<: *config-shared
    image: ${DOCKER_IMAGE_BLUE}
    container_name: blue
    volumes:
      - ./apache/blue.index.php:/var/www/html/public/index.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blue.loadbalancer.server.port=8080"
      - "traefik.http.services.blue.loadbalancer.server.scheme=http"
      - "traefik.http.services.blue.loadbalancer.healthcheck.port=8080"
      - "traefik.http.services.blue.loadbalancer.healthcheck.interval=2s"
      - "traefik.http.services.blue.loadbalancer.healthcheck.timeout=10s"

  green:
    <<: *config-shared
    image: ${DOCKER_IMAGE_GREEN}
    container_name: green
    volumes:
      - ./apache/green.index.php:/var/www/html/public/index.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.green.loadbalancer.server.port=8080"
      - "traefik.http.services.green.loadbalancer.server.scheme=http"
      - "traefik.http.services.green.loadbalancer.healthcheck.port=8080"
      - "traefik.http.services.green.loadbalancer.healthcheck.interval=2s"
      - "traefik.http.services.green.loadbalancer.healthcheck.timeout=10s"
networks:
  traefik_proxy:
    external: true
