services:

  # Provides read-only acess to docker socket for Trafik
  cetusguard:
    container_name: "cetusguard"
    image: docker.io/hectorm/cetusguard:v1@sha256:c11423117b4a370d8b16167a78294977e219615b039bd9c836d5d71336fe1703
    restart: unless-stopped
    pull_policy: always
    read_only: true
    networks:
      - "cetusguard"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      CETUSGUARD_BACKEND_ADDR: "unix:///var/run/docker.sock"
      CETUSGUARD_FRONTEND_ADDR: "tcp://:2375"
      CETUSGUARD_RULES: |
        ! Monitor events
        GET %API_PREFIX_EVENTS%
        ! List containers
        GET %API_PREFIX_CONTAINERS%/json
        ! Inspect a container
        GET %API_PREFIX_CONTAINERS%/%CONTAINER_ID_OR_NAME%/json
      CETUSGUARD_LOG_LEVEL: "7"

  loadbalancer:
    image: traefik:v3.2@sha256:990bbdb0a9174b0d441317a63188e41c63795380db42b36ed920543e27ce04c9
    container_name: traefik
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./traefik/certs/cert.key:/traefik/certs/cert.key:ro
      - ./traefik/certs/cert.crt:/traefik/certs/cert.crt:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - ${BIND_IP}:80:80
      - ${BIND_IP}:443:443
    networks:
      - traefik_proxy
      - cetusguard
      - dynamic

  # Serve dynamic yaml template via HTTP
  dynamic:
    image: nginx:stable-alpine3.20@sha256:35e3238f2f0925a505d5d697df9a9148db9a0c78e89fd2e253919047b3cec824
    container_name: dynamic
    restart: unless-stopped
    pull_policy: always
    environment:
      URL_MAIN: ${URL_MAIN}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/dynamic/http.routers.main.yml:/usr/share/nginx/html/http.routers.main.yml:ro
      - ./nginx/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    networks:
      - dynamic

networks:
  cetusguard:
  dynamic:
  traefik_proxy:
    external: true
